[theme]
primaryColor = "#6200EE"  # Purple color for buttons
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F0F5"  # Light grey for sections
textColor = "#262730"  # Dark text for readability
font = "sans serif"  # A modern sans-serif font for clarity
