[theme]
primaryColor = "#6200EE"  # Purple color for buttons
backgroundColor = "#FFF0F5"  # Pastel Pink background
secondaryBackgroundColor = "#F5F5DC"  # Light grey for sections
textColor = "#262730"  # Dark text for readability
font = 'monospace'  # A modern sans-serif font for clarity
